markdown: redcarpet
name: BC Agile Guides Template
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: Province of British Columbia
  url: https://www.gov.bc.ca

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/bc_logo_transparent.png
logoalt: BC logo

repo_url: https://github.com/bcgov/guides-template

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
- text: Add a new page
  url: add-a-new-page/
  internal: true
  children:
  - text: Make a child page
    url: make-a-child-page/
    internal: true
- text: Add images
  url: add-images/
  internal: true
- text: Update the config file
  url: update-the-config-file/
  internal: true
  children:
  - text: Understanding the `baseurl:` property
    url: understanding-baseurl/
    internal: true
- text: GitHub setup
  url: github-setup/
  internal: true
- text: Post your guide
  url: post-your-guide/
  internal: true
- text: Advanced features
  url: advanced-features/
  internal: true

repos:
- name: BC Guides Template
  description: Main repository
  url: http://github.com/bcgov/guides-template

back_link:
  url: "http://guides.pathfinder.bcgov/"
  text: Read more BC Digital Guides

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "bc_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
